packages:
  - docs
peerDependencyRules:
  allowedVersions:
    react: "18"
minimumReleaseAgeExclude:
  - "@shikijs/*"
  - "shiki"
  - "@types/node"
  - "@types/react"
  - "@vue/language-core"
  - "vue-tsc"
  - '@oxc-minify/binding-android-arm-eabi@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-android-arm64@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-darwin-arm64@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-darwin-x64@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-freebsd-x64@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-linux-arm-gnueabihf@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-linux-arm-musleabihf@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-linux-arm64-gnu@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-linux-arm64-musl@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-linux-ppc64-gnu@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-linux-riscv64-gnu@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-linux-riscv64-musl@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-linux-s390x-gnu@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-linux-x64-gnu@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-linux-x64-musl@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-openharmony-arm64@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-wasm32-wasi@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-win32-arm64-msvc@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-win32-ia32-msvc@0.136.0 || 0.139.0'
  - '@oxc-minify/binding-win32-x64-msvc@0.136.0 || 0.139.0'
  - oxc-minify@0.136.0 || 0.139.0
  - '@typescript-eslint/eslint-plugin@8.63.0'
  - '@typescript-eslint/parser@8.63.0'
  - '@typescript-eslint/project-service@8.63.0'
  - '@typescript-eslint/scope-manager@8.63.0'
  - '@typescript-eslint/tsconfig-utils@8.63.0'
  - '@typescript-eslint/type-utils@8.63.0'
  - '@typescript-eslint/types@8.63.0'
  - '@typescript-eslint/typescript-estree@8.63.0'
  - '@typescript-eslint/utils@8.63.0'
  - '@typescript-eslint/visitor-keys@8.63.0'
  - typescript-eslint@8.63.0
  - '@algolia/client-common@5.55.2'
  - '@algolia/client-search@5.55.2'
  - '@algolia/requester-browser-xhr@5.55.2'
  - '@algolia/requester-fetch@5.55.2'
  - '@algolia/requester-node-http@5.55.2'
  - prettier@3.9.5
  - vite@8.1.4
allowBuilds:
  esbuild: true
  unrs-resolver: true
  vue-demi: true
