packages:
  - docs
peerDependencyRules:
  allowedVersions:
    react: "18"
minimumReleaseAgeExclude:
  - "@shikijs/*"
  - "shiki"
  - "@types/node"
  - "@types/react"
  - "@vue/language-core"
  - "vue-tsc"
allowBuilds:
  esbuild: true
  unrs-resolver: true
  vue-demi: true
