packages:
  - docs
peerDependencyRules:
  allowedVersions:
    react: "18"
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
  - vue-demi
ignoredBuiltDependencies:
  - core-js
  - es5-ext
minimumReleaseAgeExclude:
  - "@shikijs/*"
  - "shiki"
